Add GE01 (QGIS-lisäosien kehitys)
GispoCoding/master-training-data pull request #60
Opened 2024-09-18 13:36 UTC by JuhoErvasti

Since we're migrating from using the Jupyter Notebook format let's add the updated course here.

There's substantial changes to the contents as well:

* There is a new "exercise 0" as a Python primer
* Some of the more complex Python exercises have been removed or migrated to section 9 (extra exercises)
* Exercises 1-8 are almost completely new
  * the focus is more on starting with PyQGIS in the script editor
  * the idea is to integrate the things you learn in exercises 1-4 to the plugin development itself later on
* The sample plugin produced has been overhauled, see https://github.com/GispoCoding/pyqgis-training-sample-plugin
  * the focus is more on creating and manipulating vector layers and their geometries
  * there's also a processing algorithm included
* There's also a section touching on Qt basics before jumping into Qt Designer
* I've tried to make some of the sections more approachable by explaining things and adding gifs etc.

2024-09-20 14:39 UTC, ismogis commented on src/GE01/00_harjoitus_0.Rmd
> +Listan arvoja voi muuttaa ja poistaa, ja siihen voi lisätä arvoja.
@JuhoErvasti Pitäisikö tässä puhua alkioista arvojen sijaan?

2024-09-20 14:41 UTC, ismogis commented on src/GE01/01_harjoitus_1.Rmd
> +print("Muuttujan a arvo", 5)
@JuhoErvasti Tehtävänannossa pyydetään tulostamaan vain muuttujan arvo. Mahtaakohan sotkea kokematonta, jos tulostetaan lisäksi teksti?

2024-09-20 14:42 UTC, ismogis commented on src/GE01/02_harjoitus_2.Rmd
> +alueiden nimet **NaturalEarth**-tasolta. Valitse maanosa
@JuhoErvasti Taso ei tule oletuksena tuolla nimellä ja alla käytetään tasolle toista nimeä. Pitäisiköhän yhtenäistää?

2024-09-20 14:44 UTC, ismogis commented on src/GE01/04_harjoitus_4.Rmd
> +Luo käyttöliittymä, jossa voi valita QGIS-projektin tason, jolloin
@JuhoErvasti Tätä tehtävänantoa pitäisi selkeyttää. Ilmeisesti tarkoitus on luoda taso, jolla on suorakaiteen muotoinen polygoni, jonka koko on valitun tason laajuuden mukainen?

2024-09-20 14:45 UTC, ismogis commented on src/GE01/05_harjoitus_5.Rmd
> +Testing-laajennukseen. Vasemman palkin symbolista avautuu paneeli, jonka kahden
@JuhoErvasti "Kahden kolmion symboli" ei ole minusta oikein kuvaava. Pitäisiköhän ainakin lisäksi ympyröidä kuvasta?

2024-09-20 14:47 UTC, ismogis commented on src/GE01/06_harjoitus_6.Rmd
> +Määritellään ensin fixtuurit testeille, avaa `test-plugin/testplugin/tests/conftest.py`
@JuhoErvasti Tässä vaiheessa conftest.py:tä ei kaiketi ole vielä olemassa tuossa kansiossa. Eli pitäisi varmaan opastaa luomaan ensin.

2024-09-20 14:51 UTC, ismogis requested changes
Kokonaisuus on kerrassaan mainio! Ohjeistus toimii hiukan soveltaen myös Ubuntussa. Tein muutaman kielikorjauksen ja lisäsin muutaman kommentin. Tein näistä oman commitin, niin näet helposti mitä olen muokannut.

Lisäksi skriptieditori oli toisinaan kirjoitettu yhdysmerkillä. Ne voisi myös yhtenäistää.

2024-09-23 06:56 UTC, JuhoErvasti commented on src/GE01/00_harjoitus_0.Rmd
> +Listan arvoja voi muuttaa ja poistaa, ja siihen voi lisätä arvoja.
Joo, se lienee korrektimpi termi tässä.

2024-09-23 06:57 UTC, JuhoErvasti commented on src/GE01/01_harjoitus_1.Rmd
> +print("Muuttujan a arvo", 5)
Totta, muutan tämän. Lienee peruja Jupyter-versiosta, jossa harjoitus oli eri kontekstissa.

2024-09-23 07:02 UTC, JuhoErvasti commented on src/GE01/02_harjoitus_2.Rmd
> +alueiden nimet **NaturalEarth**-tasolta. Valitse maanosa
Minä yhtenäistän. Ehkä olisi selkein käyttää kautta linjan tason oletusnimeä, vaikka siitä tuleekin melkoinen sanahirviö.

2024-09-23 07:03 UTC, JuhoErvasti commented on src/GE01/04_harjoitus_4.Rmd
> +Luo käyttöliittymä, jossa voi valita QGIS-projektin tason, jolloin
Juuri tämä on idea. Selkeytän vielä.

2024-09-23 07:16 UTC, JuhoErvasti commented on src/GE01/05_harjoitus_5.Rmd
> +Testing-laajennukseen. Vasemman palkin symbolista avautuu paneeli, jonka kahden
Muokkaan kuvaa.

2024-09-23 07:36 UTC, JuhoErvasti commented
@ismogis Kiitos arviosta ja kielikorjauksista! Olikin näköjään paljon kirjoitusvirheitä, näin sitä tulee itse sokeaksi niille. Tein muutokset näissä commiteissa: https://github.com/GispoCoding/master-training-data/pull/60/commits/2719038b0039fcd2175bf0f15c5b0bfdd33d7b9e ja https://github.com/GispoCoding/master-training-data/pull/60/commits/bc6fa3d35085198e5c77c595abc1fcb1971355d0

2024-09-23 08:02 UTC, ismogis commented on src/GE01/02_harjoitus_2.Rmd
> +alueiden nimet **NaturalEarth**-tasolta. Valitse maanosa
@JuhoErvasti Vai kannattaisiko peräti muuttaa tason nimi dataan?

2024-09-23 08:06 UTC, ismogis commented on src/GE01/06_harjoitus_6.Rmd
> +Määritellään ensin fixtuurit testeille, avaa `test-plugin/testplugin/tests/conftest.py`
@JuhoErvasti Eikö cookiecutter luo tests-kansion suoraan test-plugin-kansion alle ja conftest.py menee sinne? Mistä tulikin mieleen, että onkohan tässä joku harjoituksissa tai minulla testatessa testikansion polku väärin?

2024-09-23 08:12 UTC, JuhoErvasti commented on src/GE01/02_harjoitus_2.Rmd
> +alueiden nimet **NaturalEarth**-tasolta. Valitse maanosa
@ismogis Niin, mietin sitä myös. Siinä on vaan että kun data on GeoPackagessa niin tason nimestä tulee joka tapauksessa vähintään kaksiosainen, ellei sitä erikseen lisää selainpaneelista gpkg-yhteyden kautta. Luulisin, että suurin osa vaan lisää tason joko pudottamalla tai Tietolähteiden Hallinnan kautta. Toki tuota tiedostonimeä voisi muuttaa, jolloin oletusnimestä tulee ainakin jonkun verran lyhyempi.

2024-09-23 08:18 UTC, JuhoErvasti commented on src/GE01/06_harjoitus_6.Rmd
> +Määritellään ensin fixtuurit testeille, avaa `test-plugin/testplugin/tests/conftest.py`
@ismogis Ah joo, mun moka! Tuossa harjoitusteksissä on näköjään virhe. Tuossa polun pitäisi olla `test-plugin/tests/conftest.py`, ja cookiecutter tekee sen ihan oikein. Tuo polku saattaa itse asiassa olla muuallakin väärin, tarkistan vielä.

2024-09-23 08:24 UTC, JuhoErvasti commented on src/GE01/06_harjoitus_6.Rmd
> +Määritellään ensin fixtuurit testeille, avaa `test-plugin/testplugin/tests/conftest.py`
@ismogis Joo, tuo oli ihan systemaattinen virhe... Korjasin kaikki polut osoittamaan oikeaan osoitteeseen.

2024-09-23 10:38 UTC, ismogis approved these changes
This looks ready to be merged. Great work!

2024-09-23 11:07 UTC, merged