Add English version of GE01 - QGIS plugin development
GispoCoding/master-training-data pull request #72
Opened 2024-10-11 12:25 UTC by JuhoErvasti

This adds the exercises of GE01 translated to english as a new course.

2024-10-11 12:30 UTC, JuhoErvasti commented
@eemilhaa Do you have time to check this? The contents themselves have already been gone over in the original Finnish version so I think for this it'd be enough to just be check that there aren't any obvious mistakes (untranslated text, grammar mistakes etc.)

2024-10-17 09:54 UTC, eemilhaa commented
@JuhoErvasti I'll have a look - next week at the latest!

2024-10-22 09:04 UTC, eemilhaa requested changes
Reviewed exercise 0, will continue with the rest

2024-10-22 09:04 UTC, eemilhaa commented on src/GE01_eng/00_exercise_0.Rmd
> +paying and the `Counter` which has a _money_ attribute and
```suggestion
paying, and the `Counter` which has a _money_ attribute and
```

2024-10-22 09:04 UTC, eemilhaa commented on src/GE01_eng/00_exercise_0.Rmd
> +our relevant information to demonstrate how the program
```suggestion
out relevant information to demonstrate how the program
```

2024-10-22 13:43 UTC, eemilhaa requested changes
Review exercises 1-6

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +using PyQt. However especially creating more complex GUIs
```suggestion
using PyQt. However, especially creating more complex GUIs
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +searching its name.
```suggestion
searching for its name.
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +Editor** which is located below from the Object Inspector.
```suggestion
Editor** which is located below the Object Inspector.
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +menu to edit the different buttons. Double click the OK button
```suggestion
menu to edit the different buttons. Double-click the OK button
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +Here you are defining QAction widgets which will me added to the QGIS
```suggestion
Here you are defining QAction widgets which will be added to the QGIS
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +1. Path to a icon file. If empty the button will have no icon.
```suggestion
1. Path to an icon file. If empty the button will have no icon.
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +4. Double click the label widget and write **Layer** as its text.
```suggestion
4. Double-click the label widget and write **Layer** as its text.
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +1. Create the core folder and add an emptry `__init__.py` file.
```suggestion
1. Create the core folder and add an empty `__init__.py` file.
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +point, line and polygon layers are shown. A connection is create from the
```suggestion
point, line and polygon layers are shown. A connection is created from the
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +Organizing the coude to different classes into the separate **ui** and
```suggestion
Organizing the code to different classes into the separate **ui** and
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +Write a simple for the plugin dialog. Create a new file
```suggestion
Write a simple test for the plugin dialog. Create a new file
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +then test fails.
```suggestion
then the test fails.
```

2024-10-22 13:43 UTC, eemilhaa commented on src/GE01_eng/06_exercise_6.Rmd
> +In the test variables are defined with which the BufferTool
```suggestion
In the test we create variables with which the BufferTool
```

2024-10-22 14:34 UTC, eemilhaa requested changes
Review exercise 7-9

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/08_exercise_8.Rmd
> +It has mostly the same structure than the example before.
```suggestion
It has mostly the same structure as the example before.
```

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/08_exercise_8.Rmd
> +between the points is added
```suggestion
* A new field "distance" is added to the source layer. The distance
between the points is added to this field.
```

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/09_extra_9.Rmd
> +Jos koosteeseen halutaan asettaa ehtoja, ne laitetaan koosteen loppuun.
```suggestion
If you need to include conditions in the comprehension, they are included at the end. 
```

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/09_extra_9.Rmd
> +With tuples you first have to create a list and create a tuple from it.
```suggestion
With tuples you first have to create a list and then create a tuple from it.
```

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/09_extra_9.Rmd
> +When using ellipses a generator is created. It evaluates only one element at a time using
```suggestion
When using parentheses a generator is created. It evaluates only one element at a time using
```

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/09_extra_9.Rmd
> +Write a list compregension `chose_number` which gets integers 0-20 changed to string so that numbers 9-18 are
```suggestion
Write a list comprehension `chose_number` which gets integers 0-20 changed to string so that numbers 9-18 are
```

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/09_extra_9.Rmd
> +## Topic 2: Lambda function
```suggestion
## Topic 2: Lambda functions
```

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/09_extra_9.Rmd
> +In Python you can define one-line lambda functions with the following syntax:
```suggestion
In Python you can define "anonymous" one-line lambda functions with the following syntax:
```
Mention anonymity

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/09_extra_9.Rmd
> +Create your own decorator funciont `timeit` which measures how much
```suggestion
Create your own decorator function `timeit` which measures how much
```

2024-10-22 14:34 UTC, eemilhaa commented on src/GE01_eng/09_extra_9.Rmd
> +decorated functino such as the docstring. Use the
```suggestion
decorated function such as the docstring. Use the
```

2024-10-22 14:41 UTC, eemilhaa commented
@JuhoErvasti I went over the exercises & made a bunch of small grammar fixes. In a couple places I also did some light rewording, but nothing too major. All in all this course looks great!

2024-10-23 06:31 UTC, JuhoErvasti commented
@eemilhaa That was quite a few mistakes left in there 😬, thank you for going over the exercises! I've committed your suggestions.

2024-10-23 06:57 UTC, eemilhaa approved these changes
@JuhoErvasti Great, looks ready to merge to me!

2024-10-23 08:32 UTC, merged